- repo: git://github.com/pre-commit/pre-commit-hooks
  sha: master
  hooks:
    - id: trailing-whitespace
    - id: check-added-large-files
    - id: check-case-conflict
    - id: check-docstring-first
    - id: check-json
    - id: check-merge-conflict
    - id: check-xml
    - id: check-yaml
    - id: end-of-file-fixer
    - id: fix-encoding-pragma
    - id: name-tests-test
    - id: requirements-txt-fixer
